{
  "hash": "ae135cd70d566eb56c12313b2501f8e4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"3 · Hypothesis testing\"\nsubtitle: \"Five research questions on fraud-relevant transaction behaviour\"\n---\n\nChapter 2 ended with patterns an analyst can *see*: heavy-tailed value\ndistributions, timing differences between the flagged and legitimate populations,\ntoken activity that looks fraud-linked, and value features that move together. Eyes\nare not evidence, though — apparent patterns in a 9,841-address snapshot can be\nnoise, scale artefacts, or both. This chapter subjects five of those observations\nto formal statistical testing.\n\nThe five research questions fall into three natural groups. Two are about **how\nvalue and activity relate** — whether busier addresses send more Ether (RQ1) and\nwhether addresses operate at a characteristic value scale (RQ2). One is about\n**behaviour over time** — whether fraudulent and legitimate addresses transact on\ndifferent rhythms (RQ3). And two are about **token ecosystems** — whether Ether\noutflow differs across dominant sent-token types (RQ4) and whether the dominant\nreceived token is associated with the fraud flag itself (RQ5). Each question gets\nthe same discipline: hypotheses stated up front, assumptions checked against an\nexplicit criterion, the appropriate test run — and a second estimator that does not\nshare the first one's assumptions, so that no conclusion in this chapter hinges on\na distributional judgement call.\n\n## Ground rules for every test\n\nTwo decisions apply throughout. First, the **working scale**: every value and\nvolume variable here is heavily right-tailed (Chapter 2 made that vivid), so tests\nthat assume anything about distribution shape operate on `log10(x + 1)` scales,\nwhile rank-based checks use the raw values they are indifferent to. Second, the\n**normality criterion**, stated explicitly rather than judged by eye: a transformed\nvariable is treated as approximately normal for large-sample purposes when its\nstandardised skew and kurtosis stay within ±3.29 and no more than 1% of\nstandardised scores exceed |3.29|. The helper below implements exactly that\nassessment, and a small plotting helper shows each distribution against its normal\nreference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(car)\n\ntrxs <- readRDS(\"data/eth_clean.rds\")\n\n# ---- Normality assessment helper -------------------------------------------\n# Standardised skew & kurtosis plus the share of |z| beyond 1.96 / 3.29 —\n# the large-sample criteria described above, made explicit and reusable.\nnormality_summary <- function(x, label) {\n  x <- x[is.finite(x)]\n  n <- length(x); m <- mean(x); s <- sd(x)\n  z <- (x - m) / s\n  m2 <- mean((x - m)^2); m3 <- mean((x - m)^3); m4 <- mean((x - m)^4)\n  skew <- m3 / m2^1.5\n  kurt <- m4 / m2^2 - 3\n  se_skew <- sqrt(6 * n * (n - 1) / ((n - 2) * (n + 1) * (n + 3)))\n  se_kurt <- 2 * se_skew * sqrt((n^2 - 1) / ((n - 3) * (n + 5)))\n  tibble(variable = label, n = n, mean = m, sd = s,\n         skew = skew, skew_std = skew / se_skew,\n         kurtosis = kurt, kurt_std = kurt / se_kurt,\n         `%|z|>1.96` = 100 * mean(abs(z) > 1.96),\n         `%|z|>3.29` = 100 * mean(abs(z) > 3.29))\n}\n\n# ---- Distribution plot helper ----------------------------------------------\ndist_plot <- function(data, var, label) {\n  ggplot(data, aes(x = .data[[var]])) +\n    geom_histogram(aes(y = after_stat(density)), bins = 40,\n                   colour = \"black\", fill = \"grey80\") +\n    stat_function(fun = dnorm, colour = \"red\",\n                  args = list(mean = mean(data[[var]], na.rm = TRUE),\n                              sd = sd(data[[var]], na.rm = TRUE))) +\n    labs(x = label, y = \"Density\") +\n    theme_minimal()\n}\n\n# Log-transformed working copies for the shape-sensitive tests.\ntrxs <- trxs %>%\n  mutate(\n    total_ether_sent_log    = log10(total_ether_sent + 1),\n    total_transactions_log  = log10(total_transactions + 1),\n    avg_val_received_log    = log10(avg_val_received + 1),\n    avg_val_sent_log        = log10(avg_val_sent + 1),\n    avg_min_sent_log        = log10(avg_min_between_sent_tnx + 1)\n  )\n```\n:::\n\n\n## RQ1 — Do addresses that transact more also send more Ether?\n\nChapter 2 showed volume and frequency both exploding across orders of magnitude;\nthe first question is whether they explode *together*. If they largely do, one is\nredundant given the other; if they only loosely do, each carries its own signal.\n\n- **H0:** there is *no* relationship between total Ether sent and total number of\n  transactions per address.\n- **Ha:** there *is* a relationship between total Ether sent and total number of\n  transactions per address.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  normality_summary(trxs$total_ether_sent_log,   \"log10(total_ether_sent + 1)\"),\n  normality_summary(trxs$total_transactions_log, \"log10(total_transactions + 1)\")\n) %>% knitr::kable(digits = 2,\n                   caption = \"Normality assessment of the transformed variables against the ±3.29 criterion.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Normality assessment of the transformed variables against the ±3.29 criterion.\n\n|variable                      |    n| mean|   sd| skew| skew_std| kurtosis| kurt_std| %&#124;z&#124;>1.96| %&#124;z&#124;>3.29|\n|:-----------------------------|----:|----:|----:|----:|--------:|--------:|--------:|-------------------:|-------------------:|\n|log10(total_ether_sent + 1)   | 9841| 1.27| 1.15| 0.76|    30.80|     0.35|     7.13|                3.09|                0.41|\n|log10(total_transactions + 1) | 9841| 1.24| 0.84| 1.09|    44.22|     1.00|    20.30|                5.05|                0.10|\n\n\n:::\n:::\n\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\ndist_plot(trxs, \"total_ether_sent_log\",   \"log10(total Ether sent + 1)\")\n```\n\n::: {.cell-output-display}\n![Total Ether sent after log transformation, with its normal reference curve.](03-inference_files/figure-html/rq1-plots-1.png){width=768}\n:::\n\n```{.r .cell-code}\ndist_plot(trxs, \"total_transactions_log\", \"log10(total transactions + 1)\")\n```\n\n::: {.cell-output-display}\n![Total transactions after log transformation, with its normal reference curve.](03-inference_files/figure-html/rq1-plots-2.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrq1_pearson <- cor.test(trxs$total_ether_sent_log, trxs$total_transactions_log,\n                        method = \"pearson\")\nrq1_kendall <- cor.test(trxs$total_ether_sent, trxs$total_transactions,\n                        method = \"kendall\")\nrq1_pearson\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  trxs$total_ether_sent_log and trxs$total_transactions_log\nt = 41.083, df = 9839, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3656610 0.3993924\nsample estimates:\n      cor \n0.3826542 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(trxs, aes(total_transactions_log, total_ether_sent_log)) +\n  geom_point(alpha = 0.15, size = 0.6) +\n  geom_smooth(method = \"lm\", colour = \"red\") +\n  labs(title = \"Outflow rises with activity — but loosely\",\n       x = \"log10(total transactions + 1)\", y = \"log10(total Ether sent + 1)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Each point is an address. The association is clearly positive — and clearly loose: at any activity level, outflow still spans several orders of magnitude.](03-inference_files/figure-html/rq1-scatter-1.png){width=768}\n:::\n:::\n\n\n**Finding.** A statistically significant positive association:\nPearson *r* = 0.383\n(*p* < 0.001) on the transformed scales,\nwith Kendall's τ = 0.217 on the raw ranks confirming\ndirection and significance. The association is real but **weak-to-moderate** —\ntransaction *count* alone is a poor proxy for Ether *volume*. That looseness is\nitself informative: volume- and frequency-based signals carry partially independent\ninformation about an address, a fact the regression chapters will lean on.\n\n## RQ2 — Do high-value receivers also send high values?\n\nThe second value question is about *scale of operation*: does an address that\nreceives large average amounts also send large average amounts — retail behaviour\nstaying retail, whale behaviour staying whale?\n\n- **H0:** there is no positive correlation between the average Ether value received\n  and the average Ether value sent.\n- **Ha:** there is a positive correlation between the average Ether value received\n  and the average Ether value sent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  normality_summary(trxs$avg_val_received_log, \"log10(avg_val_received + 1)\"),\n  normality_summary(trxs$avg_val_sent_log,     \"log10(avg_val_sent + 1)\")\n) %>% knitr::kable(digits = 2,\n                   caption = \"Normality assessment for the average-value variables.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Normality assessment for the average-value variables.\n\n|variable                    |    n| mean|   sd| skew| skew_std| kurtosis| kurt_std| %&#124;z&#124;>1.96| %&#124;z&#124;>3.29|\n|:---------------------------|----:|----:|----:|----:|--------:|--------:|--------:|-------------------:|-------------------:|\n|log10(avg_val_received + 1) | 9841| 0.79| 0.82| 1.13|    45.74|     0.50|    10.12|                4.38|                0.26|\n|log10(avg_val_sent + 1)     | 9841| 0.72| 0.77| 1.04|    42.07|     0.34|     6.80|                4.66|                0.14|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrq2_pearson <- cor.test(trxs$avg_val_received_log, trxs$avg_val_sent_log,\n                        method = \"pearson\", alternative = \"greater\")\nrq2_kendall <- cor.test(trxs$avg_val_received, trxs$avg_val_sent,\n                        method = \"kendall\", alternative = \"greater\")\nrq2_pearson\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  trxs$avg_val_received_log and trxs$avg_val_sent_log\nt = 176.52, df = 9839, p-value < 2.2e-16\nalternative hypothesis: true correlation is greater than 0\n95 percent confidence interval:\n 0.8677458 1.0000000\nsample estimates:\n      cor \n0.8717837 \n```\n\n\n:::\n:::\n\n\n**Finding.** A significant positive correlation —\n*r* = 0.872,\nτ = 0.664\n(both *p* < 0.001) — addresses receiving\nlarger average values also send larger average values. Addresses do operate at a\ncharacteristic value scale, which is exactly why the *conditional* questions of the\nregression chapters (what happens at a *fixed* activity level) are the interesting\nones.\n\n## RQ3 — Does sending cadence differ between fraudulent and legitimate addresses?\n\nFrom value to time. Chapter 2's behavioural sections suggested the two populations\nmove to different rhythms; this is the formal version of that comparison. Only\naddresses with at least one sent transaction — a defined cadence — enter it.\n\n- **H0:** the average time between sent transactions does not differ between\n  fraudulent and legitimate addresses.\n- **Ha:** the average time between sent transactions differs between fraudulent and\n  legitimate addresses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrq3 <- trxs %>% filter(is.finite(avg_min_sent_log), avg_min_between_sent_tnx > 0)\n\nrq3 %>%\n  group_by(flag_f) %>%\n  summarise(n = n(),\n            mean_log = mean(avg_min_sent_log),\n            sd_log = sd(avg_min_sent_log),\n            median_minutes = median(avg_min_between_sent_tnx)) %>%\n  knitr::kable(digits = 2,\n               caption = \"Sending cadence by group.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sending cadence by group.\n\n|flag_f     |    n| mean_log| sd_log| median_minutes|\n|:----------|----:|--------:|------:|--------------:|\n|Legitimate | 5589|     2.31|   1.32|         158.74|\n|Fraudulent |  730|     3.24|   0.96|        1897.09|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrq3_levene <- leveneTest(avg_min_sent_log ~ flag_f, data = rq3)\nrq3_welch  <- t.test(avg_min_sent_log ~ flag_f, data = rq3, var.equal = FALSE)\nrq3_mwu    <- wilcox.test(avg_min_between_sent_tnx ~ flag_f, data = rq3)\n\n# Effect sizes: Cohen's d (pooled) and rank-biserial r for the MWU check\ng <- split(rq3$avg_min_sent_log, rq3$flag_f)\nn1 <- length(g[[1]]); n2 <- length(g[[2]])\nsp <- sqrt(((n1 - 1) * var(g[[1]]) + (n2 - 1) * var(g[[2]])) / (n1 + n2 - 2))\nrq3_d  <- (mean(g[[1]]) - mean(g[[2]])) / sp\nrq3_rb <- 1 - 2 * rq3_mwu$statistic / (n1 * n2)\n\nrq3_levene\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n        Df F value    Pr(>F)    \ngroup    1  146.38 < 2.2e-16 ***\n      6317                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nrq3_welch\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  avg_min_sent_log by flag_f\nt = -23.673, df = 1124.3, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Legitimate and group Fraudulent is not equal to 0\n95 percent confidence interval:\n -1.014243 -0.858983\nsample estimates:\nmean in group Legitimate mean in group Fraudulent \n                2.307567                 3.244180 \n```\n\n\n:::\n:::\n\n\n**Finding.** Levene's test indicates unequal variances\n(*p* < 0.001), so Welch's *t*-test is\nthe primary test: the cadence difference between groups is statistically\nsignificant (*t* = -23.67,\n*p* < 0.001; Cohen's\n*d* = -0.73), and the Mann–Whitney robustness check agrees\n(rank-biserial *r* = 0.42). Fraudulent and legitimate\naddresses transact on measurably different rhythms — a genuinely *behavioural*\nfraud signal, independent of value, and one that returns as a predictor in\nChapter 5.\n\n## RQ4 — Does Ether outflow differ across dominant sent-token types?\n\nFrom individual behaviour to ecosystems. If token communities differ in how much\nEther their addresses move, \"which token dominates an address\" is context that\nlater models should not ignore. Token types with fewer than 40 addresses are\nexcluded (unstable group estimates), as is `\"None\"` — no ERC20 activity is a\ndifferent phenomenon than *which* token dominates.\n\n- **H0:** total Ether sent does not differ across the ERC20 token types most\n  frequently sent from addresses.\n- **Ha:** total Ether sent differs across the ERC20 token types most frequently\n  sent from addresses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrq4 <- trxs %>%\n  filter(erc20_most_sent_token_type != \"None\") %>%\n  add_count(erc20_most_sent_token_type, name = \"type_n\") %>%\n  filter(type_n >= 40) %>%\n  mutate(token = factor(erc20_most_sent_token_type))\n\ncount(rq4, token, sort = TRUE) %>%\n  knitr::kable(caption = \"Token types entering the comparison (n ≥ 40).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Token types entering the comparison (n ≥ 40).\n\n|token                         |   n|\n|:-----------------------------|---:|\n|EOS                           | 138|\n|OmiseGO                       | 137|\n|Golem                         | 130|\n|blockwell.ai KYC Casper Token | 128|\n|StatusNetwork                 |  61|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(rq4, aes(x = reorder(token, total_ether_sent_log, median),\n                y = total_ether_sent_log)) +\n  geom_boxplot(fill = \"grey85\", outlier.alpha = 0.25) +\n  coord_flip() +\n  labs(title = \"Different token ecosystems, different outflow profiles\",\n       x = NULL, y = \"log10(total Ether sent + 1)\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Ether outflow by dominant sent-token type, on the log scale. Both the medians and the spreads differ across ecosystems — the spread differences are why a variance-robust test is used below.](03-inference_files/figure-html/rq4-box-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrq4_levene  <- leveneTest(total_ether_sent_log ~ token, data = rq4)\nrq4_welch   <- oneway.test(total_ether_sent_log ~ token, data = rq4,\n                           var.equal = FALSE)          # Welch's ANOVA\nrq4_kruskal <- kruskal.test(total_ether_sent_log ~ token, data = rq4)\nrq4_welch\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  total_ether_sent_log and token\nF = 14.748, num df = 4.00, denom df = 257.91, p-value = 7.276e-11\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Games–Howell post-hoc (appropriate under unequal variances)\nif (requireNamespace(\"rstatix\", quietly = TRUE)) {\n  rstatix::games_howell_test(rq4, total_ether_sent_log ~ token) %>%\n    filter(p.adj < 0.05) %>%\n    arrange(p.adj) %>%\n    head(10) %>%\n    knitr::kable(digits = 3,\n                 caption = \"Significant Games–Howell pairwise contrasts (top 10).\")\n} else {\n  cat(\"Install `rstatix` for the Games–Howell post-hoc table.\")\n}\n```\n\n::: {.cell-output-display}\n\n\nTable: Significant Games–Howell pairwise contrasts (top 10).\n\n|.y.                  |group1                        |group2        | estimate| conf.low| conf.high| p.adj|p.adj.signif |\n|:--------------------|:-----------------------------|:-------------|--------:|--------:|---------:|-----:|:------------|\n|total_ether_sent_log |EOS                           |Golem         |   -0.895|   -1.275|    -0.516| 0.000|****         |\n|total_ether_sent_log |Golem                         |OmiseGO       |    0.937|    0.535|     1.339| 0.000|****         |\n|total_ether_sent_log |Golem                         |StatusNetwork |    0.638|    0.187|     1.088| 0.001|**           |\n|total_ether_sent_log |blockwell.ai KYC Casper Token |OmiseGO       |    0.594|    0.137|     1.050| 0.004|**           |\n|total_ether_sent_log |blockwell.ai KYC Casper Token |EOS           |    0.552|    0.115|     0.989| 0.005|**           |\n\n\n:::\n:::\n\n\n**Finding.** With unequal variances\n(Levene *p* < 0.001), Welch's ANOVA\nfinds a significant token-type effect on Ether outflow\n(*F* = 14.75,\n*p* < 0.001), confirmed by Kruskal–Wallis\n(*p* < 0.001); the post-hoc contrasts\nidentify which specific token ecosystems are associated with heavier outflows.\n\n## RQ5 — Is the dominant received token associated with fraud?\n\nThe final question turns the token lens onto the label itself. Low-frequency token\ntypes (< 40 addresses) are aggregated into `\"Low Count\"` so that expected cell\ncounts support the χ² approximation; `\"None\"` is retained as a meaningful category.\n\n- **H0:** there is no association between the most frequently received ERC20 token\n  type and the fraud flag.\n- **Ha:** there is an association between the most frequently received ERC20 token\n  type and the fraud flag.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrq5 <- trxs %>%\n  add_count(erc20_most_rec_token_type, name = \"type_n\") %>%\n  mutate(token_rec = ifelse(type_n < 40, \"Low Count\", erc20_most_rec_token_type))\n\nrq5_tab  <- table(rq5$token_rec, rq5$flag_f)\nrq5_chi  <- chisq.test(rq5_tab)\nrq5_cram <- sqrt(rq5_chi$statistic /\n                 (sum(rq5_tab) * (min(dim(rq5_tab)) - 1)))   # Cramér's V\nrq5_chi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  rq5_tab\nX-squared = 3586.4, df = 17, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.table(rq5_tab, margin = 1) %>%\n  as.data.frame.matrix() %>%\n  tibble::rownames_to_column(\"token\") %>%\n  arrange(desc(Fraudulent)) %>%\n  head(10) %>%\n  knitr::kable(digits = 3,\n               caption = \"Fraud share by dominant received token — the ten most fraud-associated types.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Fraud share by dominant received token — the ten most fraud-associated types.\n\n|token                         | Legitimate| Fraudulent|\n|:-----------------------------|----------:|----------:|\n|Blockwell say NOTSAFU         |      0.000|      1.000|\n|GSENetwork                    |      0.000|      1.000|\n|blockwell.ai KYC Casper Token |      0.400|      0.600|\n|VIU                           |      0.700|      0.300|\n|Tronix                        |      0.737|      0.263|\n|INS Promo                     |      0.773|      0.227|\n|Livepeer Token                |      0.778|      0.222|\n|Low Count                     |      0.805|      0.195|\n|XENON                         |      0.834|      0.166|\n|None                          |      0.840|      0.160|\n\n\n:::\n:::\n\n\n**Finding.** The association is statistically significant\n(χ² = 3586.4, df = 17,\n*p* < 0.001) with effect size Cramér's\n*V* = 0.6: *which* token dominates an address's\ninflow is informative about its fraud status. The table above also foreshadows a\ntheme Chapter 5 examines critically — some token types are so strongly\nfraud-associated that the question becomes *why*, and the answer turns out to\nmatter a great deal for any predictive use of this data.\n\n## What the tests established\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: All five hypotheses in one view. In every case the robustness check agreed with the primary test.\n\n|RQ |Question                       |Primary test                 |Robustness     |Verdict                     |\n|:--|:------------------------------|:----------------------------|:--------------|:---------------------------|\n|1  |Ether sent × transaction count |Pearson (log)                |Kendall's τ    |Ha: positive, weak–moderate |\n|2  |Avg value received × sent      |Pearson (log, one-sided)     |Kendall's τ    |Ha: positive, strong        |\n|3  |Sending cadence × fraud        |Welch's t (log)              |Mann–Whitney U |Ha: groups differ           |\n|4  |Ether sent × sent-token type   |Welch's ANOVA + Games–Howell |Kruskal–Wallis |Ha: token effect            |\n|5  |Received-token type × fraud    |χ² independence + Cramér's V |—              |Ha: associated              |\n\n\n:::\n:::\n\n\nFive questions, five rejections of the null — and, more importantly for what\nfollows, none of them fragile: every verdict was confirmed by an estimator that\ndoes not share the primary test's assumptions. Two threads now lead onward. The\nbehavioural and value findings (RQ1–3) set up Chapter 4's *conditional* question —\nat a fixed activity level, what remains in an address's balance, and does fraud\nshift it? And the token findings (RQ4–5) set up Chapter 5's — do the behavioural\nsignals predict the flag, and does token context change what they mean? Everything\nhere is inference about associations; prediction, with all its extra honesty\nrequirements, comes next.\n",
    "supporting": [
      "03-inference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}