{
  "hash": "a1b9d0a210aefd9225e3fb742dca6303",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"5 · Predicting fraud\"\nsubtitle: \"From behavioural signals to flag probabilities — read with a fraud analyst's skepticism\"\n---\n\nChapter 3 established that *which* token dominates an address's inflow is\nassociated with its fraud status. This chapter turns from association to\nconditional prediction: **can transaction behaviour — how much an address\ntransacts, how much of that is token activity, and how quickly it sends — predict\nthe likelihood of a fraud flag? And does the token ecosystem change what those\nbehaviours mean?** The goal is inferential understanding of the signals, not a\ndeployable classifier; that distinction ends up mattering more here than in any\nother chapter.\n\n## The analysis sample — and what the missing data quietly revealed\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(broom)\nlibrary(car)\nlibrary(pROC)\n\ntrxs <- readRDS(\"data/eth_clean.rds\")\n\nlr <- trxs %>%\n  filter(!is.na(total_erc20_tnxs)) %>%\n  add_count(erc20_most_rec_token_type, name = \"type_n\") %>%\n  mutate(\n    token_rec  = ifelse(type_n < 40, \"Low Count\", erc20_most_rec_token_type),\n    token_rec  = relevel(factor(token_rec), ref = \"None\"),\n    tnx_log    = log10(total_transactions + 1),\n    erc20_log  = log10(total_erc20_tnxs + 1),\n    avgmin_log = log10(avg_min_between_sent_tnx + 1)\n  )\n\nn_excl  <- sum(is.na(trxs$total_erc20_tnxs))\nexcl_fr <- sum(trxs$flag[is.na(trxs$total_erc20_tnxs)])\ncat(nrow(lr), \"addresses in sample;\", sum(lr$flag), \"flagged\",\n    sprintf(\"(%.1f%%; majority-class baseline accuracy %.1f%%)\",\n            100 * mean(lr$flag), 100 * (1 - mean(lr$flag))))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n9012 addresses in sample; 1350 flagged (15.0%; majority-class baseline accuracy 85.0%)\n```\n\n\n:::\n:::\n\n\nThe model needs the ERC20 aggregates, so the 829 addresses lacking them are\nexcluded — and that routine step surfaced something worth pausing on. The fraud\nshare drops from 22.1% to 15.0%, which is a\nlarge move for a 8% exclusion, and the reason is stark: **all 829 of the\nexcluded addresses are flagged fraudulent** (829/829). In other\nwords, in this dataset \"ERC20 data missing\" perfectly predicts the label. The most\nplausible cause is mechanical — the fraud-address list appears to have been\nassembled separately and joined in, with the ERC20 aggregates never computed for\npart of that batch — which makes missingness an artefact of dataset construction,\nnot a behaviour of fraudsters. The practical consequences: missingness must never\nbe used as a feature on this data, and everything below speaks for token-active\naddresses only. Low-frequency token types (< 40 addresses) are pooled into a\n`\"Low Count\"` level so group estimates stay stable, and `\"None\"` — no dominant\nERC20 inflow — is kept as the meaningful reference category.\n\n## Model 1: what behaviour alone says\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- glm(flag ~ tnx_log + erc20_log + avgmin_log,\n          family = binomial, data = lr)\n\ntidy(m1, exponentiate = TRUE, conf.int = TRUE) %>%\n  knitr::kable(digits = 3,\n               caption = \"Model 1 — odds ratios with 95% CIs. Each OR is the multiplicative change in fraud odds for a ×10 change in the predictor.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Model 1 — odds ratios with 95% CIs. Each OR is the multiplicative change in fraud odds for a ×10 change in the predictor.\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |    0.675|     0.060|    -6.528|       0|    0.600|     0.760|\n|tnx_log     |    0.204|     0.070|   -22.820|       0|    0.178|     0.234|\n|erc20_log   |    4.601|     0.070|    21.925|       0|    4.016|     5.277|\n|avgmin_log  |    0.835|     0.022|    -8.165|       0|    0.799|     0.872|\n\n\n:::\n:::\n\n\n\n\nRead on the ×10 scale, the three effects sketch a coherent behavioural\nfingerprint. A ×10 increase in **ordinary transactions** multiplies the fraud odds\nby 0.2 — sustained, plain on-chain activity is what\nlegitimacy looks like. A ×10 increase in **ERC20 token transactions** multiplies\nthe odds by 4.6 — the flagged population is\ntoken-transfer-heavy. And a ×10 *longer* **average gap between sent transactions**\nmultiplies the odds by 0.83: quicker sending rhythms\nlean fraudulent, echoing the cadence difference found in Chapter 3. Fraud, in this\ndata, looks token-heavy, plain-transaction-light, and fast. The model's McFadden\npseudo-R² is 0.12 and the VIFs below confirm the three\nsignals are not proxies for one another.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif(m1) %>% knitr::kable(col.names = \"VIF\",\n                         caption = \"Variance inflation factors — the three behavioural signals carry distinct information.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Variance inflation factors — the three behavioural signals carry distinct information.\n\n|           |      VIF|\n|:----------|--------:|\n|tnx_log    | 2.183933|\n|erc20_log  | 2.320851|\n|avgmin_log | 1.332773|\n\n\n:::\n:::\n\n\n## From scores to decisions\n\nA logistic model outputs probabilities; a fraud screen must output decisions, and\nthe gap between those two is where the operational honesty lives.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroc1 <- roc(lr$flag, fitted(m1), quiet = TRUE)\nplot(roc1, legacy.axes = TRUE, col = \"#2C7FB8\",\n     main = sprintf(\"Behaviour-only model — AUC %.2f\", auc(roc1)))\n```\n\n::: {.cell-output-display}\n![Model 1 discrimination. AUC summarises ranking quality across all possible thresholds — it says nothing about any particular operating point.](05-fraud-logr_files/figure-html/m1-roc-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred1 <- factor(ifelse(fitted(m1) >= 0.5, \"Fraudulent\", \"Legitimate\"),\n                levels = c(\"Legitimate\", \"Fraudulent\"))\ncm <- table(pred1, lr$flag_f)\n\ndata.frame(\n  ` ` = c(\"Predicted: Legitimate\", \"Predicted: Fraudulent\"),\n  `Actual: Legitimate` = cm[, \"Legitimate\"],\n  `Actual: Fraudulent` = cm[, \"Fraudulent\"],\n  check.names = FALSE\n) %>%\n  knitr::kable(row.names = FALSE,\n               caption = \"Confusion matrix at the default 0.5 threshold.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Confusion matrix at the default 0.5 threshold.\n\n|                      | Actual: Legitimate| Actual: Fraudulent|\n|:---------------------|------------------:|------------------:|\n|Predicted: Legitimate |               7594|               1085|\n|Predicted: Fraudulent |                 68|                265|\n\n\n:::\n\n```{.r .cell-code}\ntibble(\n  metric = c(\"AUC\", \"Accuracy\", \"Sensitivity (fraud recall)\", \"Specificity\"),\n  value = c(as.numeric(auc(roc1)),\n            sum(diag(cm)) / sum(cm),\n            cm[\"Fraudulent\", \"Fraudulent\"] / sum(cm[, \"Fraudulent\"]),\n            cm[\"Legitimate\", \"Legitimate\"] / sum(cm[, \"Legitimate\"]))\n) %>% knitr::kable(digits = 3, caption = \"Operating characteristics at the 0.5 threshold.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Operating characteristics at the 0.5 threshold.\n\n|metric                     | value|\n|:--------------------------|-----:|\n|AUC                        | 0.711|\n|Accuracy                   | 0.872|\n|Sensitivity (fraud recall) | 0.196|\n|Specificity                | 0.991|\n\n\n:::\n:::\n\n\nThe matrix tells the story the accuracy number hides. At the default threshold the\nmodel catches 265 of the\n1350 flagged addresses\n(sensitivity 20%)\nwhile raising only 68 false alarms — and still\nposts 87% accuracy, because with\n85% of addresses legitimate, accuracy mostly rewards saying \"legitimate\". The 0.5\nthreshold is a statistical default, not a policy: in a real fraud operation the\nthreshold is set by the relative cost of a missed fraud versus an investigation,\nand lowering it here would trade a manageable rise in false alarms for a large\ngain in recall. The behavioural signals rank addresses usefully\n(AUC 0.71); what to *do* with the ranking is a\nbusiness decision.\n\n## Model 2: does the token ecosystem change what behaviour means?\n\nChapter 3 found the dominant received token *associated* with fraud; the sharper\nquestion is whether it *moderates* the behavioural signals — whether the same\npattern of activity means something different inside different token communities.\nModel 2 interacts all three behavioural predictors with the token factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- glm(flag ~ (tnx_log + erc20_log + avgmin_log) * token_rec,\n          family = binomial, data = lr)\n\n# Wald intervals: several token × behaviour cells contain (almost) only one\n# class, so profile-likelihood CIs do not converge for those terms.\ntidy(m2) %>%\n  mutate(OR = exp(estimate),\n         conf.low = exp(estimate - 1.96 * std.error),\n         conf.high = exp(estimate + 1.96 * std.error)) %>%\n  select(term, OR, conf.low, conf.high, p.value) %>%\n  filter(p.value < 0.05) %>%\n  arrange(p.value) %>%\n  knitr::kable(digits = 3,\n               caption = \"Model 2 — significant terms only (Wald 95% CIs; full table in the folded code).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Model 2 — significant terms only (Wald 95% CIs; full table in the folded code).\n\n|term                                           |           OR|  conf.low|    conf.high| p.value|\n|:----------------------------------------------|------------:|---------:|------------:|-------:|\n|token_recLow Count                             | 1.459604e+03|   506.676| 4.204747e+03|   0.000|\n|(Intercept)                                    | 3.000000e-03|     0.001| 9.000000e-03|   0.000|\n|token_recLivepeer Token                        | 7.562441e+05| 36117.485| 1.583458e+07|   0.000|\n|erc20_log:token_recLivepeer Token              | 0.000000e+00|     0.000| 0.000000e+00|   0.000|\n|token_recXENON                                 | 3.364772e+03|   344.826| 3.283303e+04|   0.000|\n|token_recTronix                                | 6.183820e+02|    80.319| 4.760964e+03|   0.000|\n|erc20_log:token_recXENON                       | 1.000000e-03|     0.000| 8.000000e-03|   0.000|\n|erc20_log:token_recLow Count                   | 1.800000e-02|     0.004| 7.600000e-02|   0.000|\n|token_recDATAcoin                              | 1.891263e+04|   523.198| 6.836568e+05|   0.000|\n|token_recblockwell.ai KYC Casper Token         | 1.965601e+05|  1397.492| 2.764658e+07|   0.000|\n|erc20_log                                      | 3.083700e+01|     7.436| 1.278870e+02|   0.000|\n|token_recINS Promo                             | 5.086892e+04|   350.530| 7.382106e+06|   0.000|\n|erc20_log:token_recDATAcoin                    | 0.000000e+00|     0.000| 0.000000e+00|   0.000|\n|tnx_log:token_recblockwell.ai KYC Casper Token | 3.700000e-02|     0.007| 1.990000e-01|   0.000|\n|tnx_log:token_recVIU                           | 2.300000e-02|     0.002| 2.680000e-01|   0.003|\n|tnx_log:token_recLivepeer Token                | 1.430000e-01|     0.039| 5.230000e-01|   0.003|\n|token_recVIU                                   | 5.249525e+03|    15.544| 1.772910e+06|   0.004|\n|tnx_log:token_recTronix                        | 2.390000e-01|     0.083| 6.850000e-01|   0.008|\n|tnx_log:token_recLow Count                     | 4.080000e-01|     0.210| 7.910000e-01|   0.008|\n|avgmin_log:token_recDATAcoin                   | 2.386000e+00|     1.215| 4.685000e+00|   0.012|\n|erc20_log:token_recTronix                      | 1.060000e-01|     0.018| 6.370000e-01|   0.014|\n|token_recKickCoin                              | 6.731249e+18|  5478.739| 8.270099e+33|   0.014|\n|token_recEOS                                   | 9.960050e+04|     9.085| 1.091914e+09|   0.015|\n|tnx_log:token_recINS Promo                     | 3.000000e-03|     0.000| 3.340000e-01|   0.016|\n|avgmin_log:token_recKickCoin                   | 0.000000e+00|     0.000| 3.310000e-01|   0.024|\n|tnx_log:token_recKickCoin                      | 0.000000e+00|     0.000| 2.370000e-01|   0.026|\n|tnx_log:token_recOmiseGO                       | 1.840000e-01|     0.034| 9.980000e-01|   0.050|\n\n\n:::\n:::\n\n\nThe table already hints at what is happening: token-level odds ratios in the\nhundreds of thousands, interaction ORs indistinguishable from zero. Estimates that\nextreme are the signature of near-empty cells — token groups where one class\nbarely occurs — pushing coefficients toward the boundary. They are shown for\ncompleteness, not interpreted individually; the trustworthy comparison is at the\nmodel level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlrt <- anova(m1, m2, test = \"Chisq\")\nroc2 <- roc(lr$flag, fitted(m2), quiet = TRUE)\n\ntibble(model = c(\"M1: behaviour only\", \"M2: + token-type interactions\"),\n       pseudo_R2 = c(mcfadden(m1), mcfadden(m2)),\n       AUC = c(as.numeric(auc(roc1)), as.numeric(auc(roc2))),\n       AIC = c(AIC(m1), AIC(m2))) %>%\n  knitr::kable(digits = 3,\n               caption = \"Model comparison. The likelihood-ratio test for the added terms is decisive (p < .001) — the interesting question is why.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Model comparison. The likelihood-ratio test for the added terms is decisive (p < .001) — the interesting question is why.\n\n|model                         | pseudo_R2|   AUC|      AIC|\n|:-----------------------------|---------:|-----:|--------:|\n|M1: behaviour only            |     0.117| 0.711| 6727.439|\n|M2: + token-type interactions |     0.753| 0.983| 2023.764|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(roc1, col = \"#2C7FB8\", legacy.axes = TRUE,\n     main = \"Adding token context: dramatic — and suspicious\")\nplot(roc2, col = \"#D95F02\", add = TRUE)\nlegend(\"bottomright\",\n       legend = c(sprintf(\"M1: behaviour only (AUC %.2f)\", auc(roc1)),\n                  sprintf(\"M2: + token context (AUC %.2f)\", auc(roc2))),\n       col = c(\"#2C7FB8\", \"#D95F02\"), lwd = 2, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![Both models' ROC curves. The jump is real in-sample — and the next paragraphs explain why it should not be taken at face value.](05-fraud-logr_files/figure-html/roc-both-1.png){width=768}\n:::\n:::\n\n\n\n\n### Reading the jump carefully\n\nAn AUC of 0.98 from a logistic regression should\nraise an eyebrow before it raises applause, and here the skepticism pays off. Part\nof the improvement is genuine segment structure — Chapter 3's association result\nmade that expected. But a decisive part of it is simpler:\n**2 token levels in this sample coincide perfectly with the fraud\nflag** — *Blockwell say NOTSAFU* (n = 779) and *GSENetwork* (n = 80)\nare flagged fraudulent without exception. Both are known spam-airdrop tokens, and\nthe likely mechanism runs through how the dataset was built: the fraud list appears\nto draw heavily on addresses swept up in those scam ecosystems, so receiving these\ntokens is partly a *consequence* of how the label was constructed rather than an\nindependent behavioural signal. Combined with the missingness artefact found\nearlier, the message is consistent: this dataset rewards models that memorise its\nconstruction.\n\nFor anyone taking this analysis toward a production model, three practices follow\nnaturally: validate out-of-time rather than in-sample, so construction artefacts\nstop paying; ablate token *identity* and check how much discrimination survives on\nbehaviour alone (here, an AUC of 0.71); and treat\ntoken context as segment information whose meaning must be re-learned as scam\necosystems change, not as a stable feature. Read that way, Model 2 is best\nunderstood as strong evidence that token context *carries* signal — and a worked\nexample of why a fraud analyst never deploys an in-sample 0.98.\n\n## What this chapter established\n\nBehaviour alone ranks addresses usefully — token-heavy, plain-transaction-light,\nfast-cadence profiles carry materially higher flag odds — and token context adds\nreal but contaminated lift whose honest assessment requires validation this\ncross-sectional dataset cannot provide. The estimates speak for token-active\naddresses, against a label of undocumented provenance, in-sample only; the\ndeployment-grade treatment of this problem — held-out protocols, imbalance\nhandling, cost-sensitive thresholds — is the subject of the dedicated\nmachine-learning project that this suite's conclusions point toward.\n",
    "supporting": [
      "05-fraud-logr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}